version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - errorlint
    - exhaustive
    - gocritic
    - misspell
    - nilerr
    - nolintlint
    - revive
    - unconvert
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
