run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused

issues:
  exclude-use-default: false
